### ISSUE TITLE
Login/Logout-Button

### ISSUE THREAD

**Issue by Schmoerls** [MME-Aufgaben-im-Winter-2021/projects-crity-mme-2021-22#28]
Als Nutzer möchte ich einen Button zum Login oder Logout auf der Editor Seite zur Verfügung stehen haben und im Falle des Login auch zur Loginseite weitergeleitet werden.

**Comment by mum37352** [comment]
Implemented in branch `logout`.

**Comment by mum37352** [comment]
Now in `dev`.
